---
language: ruby
cache: bundler

ruby:
  - '2.5'
  - '2.6'
  - '2.7'
  - '3.0'
  - '3.1'

before_install:
  - gem install bundler -v 2.1.4

gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_61.gemfile
  - gemfiles/rails_70.gemfile

matrix:
  exclude:
    - gemfile: gemfiles/rails_70.gemfile
      ruby: 2.5
    - gemfile: gemfiles/rails_70.gemfile
      ruby: 2.6

script: bundle exec rake spec
